# spring configuration
spring:
   application:
      name: emaillist08
      version: 1.0.0
   profiles:
      active: development


---
# common profile
spring:
   mvc:
      static-path-pattern: /assets/**
   web:
      resources:
         static-locations: classpath:/assets/
   thymeleaf:      
      check-template-location: true
      enable-spring-el-compiler: true	  
      mode: HTML
      prefix: classpath:templates/      	  
      suffix : .html

mybatis:
   config-location: classpath:mybatis/configuration.xml      

server:
   error:
      whitelabel:
         enabled: false
      path: /error
   servlet:
      context-path: /


---
# development profile
spring:
   config:
      activate:
         on-profile: development

   devtools:
      restart:
         enabled: true
      livereload:
         enabled: true

   thymeleaf:
      cache: false

   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://192.168.66.4:3306/webdb?charset=utf8
      username: webdb
      password: webdb
      hikari:
         minimum-idle: 10
         maximum-pool-size: 20

server:
   port: 8080
    
logging:
   pattern:
      console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
   level:
      root: INFO


---
# production profile
spring:
   config:
      activate:
         on-profile: production

   thymeleaf:
      cache: true
   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://192.168.66.4:3306/webdb?charset=utf8
      username: webdb
      password: webdb
      hikari:
         minimum-idle: 10
         maximum-pool-size: 20

server:
   port: 8091

logging:
   pattern:
      file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
   logback:
      rollingpolicy:
         file-name-pattern: "logs/${spring.application.name}.%d{yyyy-MM-dd}.%i.log.zip"
         max-file-size: 10MB
         max-history: 10
   file:
      name: logs/${spring.application.name}.log
   level:
      root: WARN
      emaillist:
         exception: ERROR