spring:
   application:
      name: emaillist
   profiles:
      active: development




---
# configuration: common
spring:
   mvc:
      static-path-pattern: /assets/**
      throw-exception-if-no-handler-found: true
   web:
      resources:
         static-locations: classpath:/assets/
   thymeleaf:
      prefix : classpath:templates/
      check-template-location: true
      mode: HTML5
      suffix : .html

server:
   error:
      whitelabel:
         enabled: false
      path: /error
   servlet:
      context-path: /
      encoding:
         charset: utf-8
         enabled: true
         
               

---
# configuration: development
spring:
   config:
      activate:
         on-profile: development
         
   devtools:
      livereload:
         enabled: true         
   security:
      oauth2:
         client:
            provider:
                keycloak-authorization-server:
                   issuer-uri: http://localhost:5555/realms/poscodx2023-realm
                   authorization-uri: http://localhost:5555/realms/poscodx2023-realm/protocol/openid-connect/auth
                   token-uri: http://localhost:5555/realms/poscodx2023-realm/protocol/openid-connect/token
            registration:
                emaillist-oauth2-client:
                   provider: keycloak-authorization-server                  
                   authorization-grant-type: authorization_code
                   redirect-uri: "http://localhost:8080/login/oauth2/code/{registrationId}"
                   client-id: emaillist
                   client-secret: 649Yde3fNbCBxHG2AxAI8zF70M5R9PjM
                   scope: [openid, profile, email, roles]

server:
   port: 8080
         
logging:
   pattern:
      console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
   level:
      root: INFO



      
---
# configuration: production
spring:
   config:
      activate:
         on-profile: production

   security:
      oauth2:
         client:
            provider:
                keycloak-authorization-server:
                   issuer-uri: http://192.168.66.4:5555/realms/poscodx2023-realm
                   authorization-uri: http://192.168.66.4:5555/realms/poscodx2023-realm/protocol/openid-connect/auth
                   token-uri: http://192.168.66.4:5555/realms/poscodx2023-realm/protocol/openid-connect/token
            registration:
                emaillist-oauth2-client:
                   provider: keycloak-authorization-server                  
                   authorization-grant-type: authorization_code
                   redirect-uri: "http://192.168.66.4:8080/login/oauth2/code/{registrationId}"
                   client-id: emaillist
                   client-secret: 649Yde3fNbCBxHG2AxAI8zF70M5R9PjM
                   scope: [openid, profile, email, roles]

server:
   port: 8097

logging:
   pattern:
      file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
   logback:
      rollingpolicy:
         file-name-pattern: "logs/${spring.application.name}.%d{yyyy-MM-dd}.%i.log.zip"
         max-file-size: 10MB
         max-history: 10
   file:
      name: logs/${spring.application.name}.log
   level:
      root: WARN
      com:
         poscodx:
            emaillist:
               exception: ERROR
