# spring configuration
spring:
   application:
      name: service-guestbook
      version: 1.0.0      
   profiles:
      active: development

---
# configuration: common
spring:
   cloud:
      config:
         enabled: true

---
# configuration: development
spring:
   config:
      activate:
         on-profile: development
      import: optional:configserver:http://localhost:7777

---
# configuration: production
spring:
   config:
      activate:
         on-profile: production
      import: optional:configserver:http://192.168.56.5:7777