# spring configuration
spring:
   application:
      name: service-emaillist
      version: 1.0.0
   profiles:
      active: development


---
# profile: common(default)
# configuration: common
spring:
   cloud:
      config:
         enabled: true

---
# configuration: development
spring:
   config:
      activate:
         on-profile: development
      import: optional:configserver:http://localhost:7777

---
# configuration: production
spring:
   config:
      activate:
         on-profile: production
      import: optional:configserver:http://192.168.66.4:7777